config/routes.rb
RevolvingChore::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :groups do
    collection do
      post 'assigned_chores/add_more_assigned_chores'
    end 
    member do
      delete 'remove_user_from_group'
      get 'chore_history'
    end
    resources :assigned_chores do
      resources :ratings do
        collection do
          post 'upsert'
          post 'archive'
        end
      end
      resources :trades do
        member do
          post 'accept'
          post 'decline'
          post 'retract'
        end
      end
      collection do
        post 'create_initial_assigned_chores'
      end
      member do
        post 'complete'
        post 'uncomplete'
      end
    end
    resources :chores
    resources :invitations do
      member do
        get 'accept'
      end
    end
  end

  resources :users do
    member do
      get 'chore_history'
    end
  end

  get "home/index"
  get "home/how_this_works"
  get "home/faq"
  get "home/login"
  
  root :to => "home#index"

  post '/oauth/request_token' => 'sessions#new'

  match '/auth/:provider/callback' => 'sessions#create',:as => 'login'
  match '/auth/failure' => 'sessions#failure'
  match '/auth/logout' => 'sessions#destroy',:as => 'logout'

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :chores
  has_many :group_maps
  has_many :users, :through => :group_maps
  has_many :assigned_chores
  has_many :invitations
  has_many :trades
  attr_accessible :name, :chore_start_date, :time_zone, :chore_period_length_days, 
    :facebook_penalty, :facebook_penalty_msg, 
    :monetary_penalty, :monetary_penalty_value,
    :email_penalty, :email_penalty_address, :email_penalty_msg 

  validates :name, :presence => true
  validates :chore_period_length_days, :presence => true
  validates :chore_period_length_days, :numericality => {:greater_than_or_equal_to => 0}
  validates_numericality_of :chore_period_length_days, :only_integer => true

  validates :chore_start_date, :presence => true

  def set_calendar_colors(event_strips)
    #returns hash of colors assigned to user. Key => Value. username => color

    users = self.users
    colors = ["#E23939", "#55C6EB", "#3DB638", "#F09C37", "#E4E43D", "#4E4EF7", "#985AF5", "#74DFB0"]
    counter = 0
    user_colors = Hash.new

    users.each do |user|
      user_colors.merge!(user.username => colors[counter % colors.length])
      counter += 1
    end

    event_strips.collect! do |event_strip|
      event_strip.collect! do |event|
        if event != nil && user_colors.has_key?(event.username)
          event.color = user_colors[event.username]
          event
        end
      end
    end

    event_strips

  end

  def current_chores
    assigned_chores = self.assigned_chores
    unless assigned_chores.empty?
      current_chores = assigned_chores.where("start_date <= ? and due_date >= ?", Date.today, Date.today).order('username ASC, name ASC')
    else
      return nil
    end
  end
  
  def user_count
    self.users.count
  end
  
  def punish(chore)
    # Social Media Penalty
    chore.user.post(self.facebook_penalty_msg) if self.facebook_penalty
    
    # nothing currently setup for monetary penalty
    
    # Mass Email Penalty
    GroupMailer.email_penalty(chore).deliver if self.email_penalty
  end
  
  def chore_history
    assigned_chores = self.assigned_chores.where('due_date < ?', Date.today).where("due_date > ?", Date.today - 3.month).order('due_date ASC, username ASC, name ASC')
  end
  
  def possible_chore_trades(user_id)
    assigned_chores = self.assigned_chores.where("user_id != ? AND status = ?", user_id, 'Not Completed').where("start_date <= ? and due_date >= ?", Date.today, Date.today).order('name ASC, username ASC')
  end
  
  def recently_completed_chores(user_id)
    chores = self.assigned_chores.joins('LEFT OUTER JOIN ratings ON (ratings.assigned_chore_id = assigned_chores.id AND ratings.user_id = ' + user_id.to_s + ')')
      .where("completion_date > NOW() - interval '7 days'")
      .where("assigned_chores.user_id != ? AND (ratings.archived = ? OR ratings.archived IS ?)", user_id, false, nil).order('name ASC, username ASC')
    unless chores.empty?
      chores
    else
      nil
    end
  end
  
  def pending_trades
    trades = self.trades.where(:status => 'Pending')
    unless trades.empty?
      trades
    else
      nil
    end
  end
  
  def chores_completed_by_week
    self.assigned_chores.select("date_trunc('week',due_date) as date,COUNT(completion_date) as count").where("due_date < ?", Time.now).where("completion_date is not null").group("date_trunc('week',due_date)").order("date_trunc('week',due_date) ASC")
  end
  
  def percentage_chores_completed_by_user
    self.assigned_chores.select("username, ROUND(COUNT(completion_date)/COUNT(id)::decimal * 100,2) as percent").where("due_date < ?", Time.now).group("username")
  end
  
  def percentage_completed_by_chore
    self.assigned_chores.select("name, ROUND(COUNT(completion_date)/COUNT(id)::decimal * 100,2) as percent").where("due_date < ?", Time.now).group("name")
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  skip_before_filter :validate_and_set_allowable_group, :only => [:new, :create]
  # GET /groups/1
  # GET /groups/1.json
  def show

    unless @current_chores = @group.current_chores
      @users = @group.users
    end

    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = @group.assigned_chores.event_strips_for_month(@shown_month)
    @event_strips = @group.set_calendar_colors(@event_strips)
    
    @recently_completed_chores = @group.recently_completed_chores(@current_user.id)
    @pending_trades = @group.pending_trades
    @group_chores_completed_by_week = @group.chores_completed_by_week
    @group_percentage_chores_completed_by_user = @group.percentage_chores_completed_by_user
    @group_percentage_completed_by_chore = @group.percentage_completed_by_chore
  end 


  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    params[:group][:chore_start_date] = Date.strptime(params[:group][:chore_start_date], "%m/%d/%Y") rescue nil
    @group = Group.new(params[:group])
    @group.users << User.find(@current_user.id)

    respond_to do |format|
      if @group.save
        flash[:notice] = "You have successfully created a group!"
        format.html { redirect_to @group }
        format.json { render json: @group, status: :created, location: @group }
      else
        flash[:error] = "Looks like something went wrong."
        format.html { render new_group_path }
        # format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    params[:group][:chore_start_date] = Date.strptime(params[:group][:chore_start_date], "%m/%d/%Y") rescue nil
    respond_to do |format|
      if @group.update_attributes(params[:group])
        AssignedChore.create_initial_assigned_chores(params[:id])
        flash[:notice] = "You have successfully updated your group!"
        format.html { redirect_to @group}
        format.json { head :no_content }
      else
        flash[:error] = "Looks like something went wrong."
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def remove_user_from_group
    @group.users.destroy(params[:user_id])

    if @group.users.empty?
      @group.assigned_chores.where('due_date >= ?', Date.today).destroy_all
      @group.destroy
      redirect_to @current_user
    else
      AssignedChore.create_initial_assigned_chores(params[:id])
      redirect_to edit_group_path(@group.id)
    end
  end
  
  def chore_history
    @chore_history = @group.chore_history
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
- if @group.errors.any?
  .alert{:style => 'font-weight:bold;'}
    = pluralize(@group.errors.count, "error")
    prohibited this task from being saved:
    .ul
      - @group.errors.full_messages.each do |msg|
        .li
          = msg
= form_for @group, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :time_zone, :class => 'control-label'
    .controls
      = f.time_zone_select :time_zone, nil, :default => cookies["time_zone"]
  .control-group
    = f.label :chore_period_length_days, :class => 'control-label'
    .controls
      = f.number_field :chore_period_length_days, :class => 'number_field'
  .control-group
    = f.label :chore_start_date, :class => 'control-label' 
    .controls
      = text_field_tag "group[chore_start_date]", @group.chore_start_date.try(:strftime, '%m/%d/%Y'), :class => "datepicker", :default => Date.today
  .control-group
    = f.label "Penalty", :class => 'control-label'
    .controls
      %label.checkbox
        = f.check_box :facebook_penalty, :class => 'check_box parent'
        Social Media Post
      .child{:class => ("hide" unless @group.facebook_penalty)}
        .control-group
          = f.label :facebook_penalty_msg, "Message", :class => 'control-label'
          .controls
            = f.text_area :facebook_penalty_msg, :class => 'text_area span6', :rows => 5    
      %label.checkbox
        = f.check_box :email_penalty, :class => 'check_box parent'
        Mass Email
      .child{:class => ("hide" unless @group.email_penalty)}
        .control-group
          = f.label :email_penalty_address, "Group Email Address", :class => 'control-label'
          .controls
            = f.text_field :email_penalty_address, :class => 'text_field'
        .control-group
          = f.label :email_penalty_msg, "Message", :class => 'control-label'
          .controls
            = f.text_area :email_penalty_msg, :class => 'text_area span6', :rows => 5    
      %label.checkbox
        = f.check_box :monetary_penalty, :class => 'check_box parent'
        Money Due
      .child{:class => ("hide" unless @group.monetary_penalty)}
        .control-group
          = f.label :monetary_penalty_value, "Amount", :class => 'control-label'
          .controls
            .input-prepend
              %span.add-on $
              = f.text_field :monetary_penalty_value, :class => 'text_field'    
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to "Cancel", :back, :class => 'btn'
      
      
      
      

app/views/groups/chore_history.html.haml
.page-header
  %h1 #{@group.name} Chore History
  %table.table.table-striped.table-bordered.table-condensed
    %tr
      %th Due Date
      %th Person
      %th Chore
      %th Status
    - if @chore_history
      - @chore_history.each do |chore|
        %tr
          %td
            = chore.due_date
          %td
            = chore.username
          %td
            = chore.name
          %td
            - if chore.status == "Completed"
              %span.label.label-success #{chore.status}
            - else
              %span.label.label-important #{chore.status}

app/views/groups/edit.html.haml
= render :partial => 'layouts/alerts'
.page-header
  %h1
    #{@group.name}
    %small
      Settings
%ul.nav.nav-tabs.remember-tab
  %li.active
    = link_to "Members", "#members", {"data-toggle" => "tab"}
  %li
    = link_to "Chores", "#chores", {"data-toggle" => "tab"}
  %li
    = link_to "Group Info", "#info", {"data-toggle" => "tab"}
.tab-content
  .tab-pane.active#members
    %table.table.table-striped.table-bordered
      %h3 Group Members
      %thead
        %tr
          %th Photo
          %th Username
          %th Actions
      %tbody
        - @group.users.each do |user|
          %tr
            %td 
            %td 
              = user.username
            %td
              = link_to "Remove", remove_user_from_group_group_path(@group, :user_id => user.id), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger'
    = link_to "Invite a Friend", new_group_invitation_path(@group), :class => "btn btn-primary modalCandidate"
  .tab-pane#chores
    %table.table.table-striped.table-bordered
      %h3 Chores
      %thead
        %tr
          %th Name
          %th Description
          %th Actions
      %tbody
        - @group.chores.each do |chore|
          %tr
            %td 
              = chore.name
            %td 
              = chore.description
            %td
              = link_to "Edit Chore", edit_group_chore_path(@group, chore), :class => 'btn btn-mini modalCandidate'
              = link_to "Remove", group_chore_path(@group, chore), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger ajaxCandidate'
    = link_to "Add a Chore", new_group_chore_path(@group), :class => "btn btn-primary modalCandidate"
  .tab-pane#info
    %h3 Edit Group Info
    = render :partial => 'form'

app/views/groups/new.html.haml
%body
  .container
    %h1 Create A Group
    = render :partial => 'form'

app/views/groups/show.html.haml
- content_for :head do
  %title #{@group.name}'s Dashboard - Revolving Chore
  %meta{:name => "description", :content => "RevolvingChore is a fully automated chore chart substitute that comes complete with punishments, trading, and much more!"}
= render :partial => 'layouts/alerts'
.page-header
  %h1
    #{@group.name}
    %small
      Dashboard
      = link_to "Edit Group", edit_group_path(@group.id), :class => "btn btn-primary"
.row
  .span4
    %ul.thumbnails
      %li
        .thumbnail
          %h5 Chores Completed by Week
          %canvas#lineGraph{:height => "150", :width => "280"}
      %li
        .thumbnail
          %h5 Chores Completed by Person (%)
          %canvas#radarGraph{:height => "250", :width => "280"}
      %li
        .thumbnail
          %h5 How Often Each Chore is Completed
          %canvas#barGraph{:height => "300", :width => "280"}
  .span8
    .row
      - if @recently_completed_chores
        %h3 Notifications
        %table.table.table-striped.table-condensed
          - @recently_completed_chores.each do |chore|
            %tr
              %td
                %strong
                  #{chore.username} 
                recently completed #{chore.name}.
              %td{:style => "width:250px"}
                = render :partial => 'ratings/form', :locals => {:group => @group, :chore => chore}
      - if @pending_trades
        %h3 Pending Trades
        %table.table.table-striped.table-condensed
          - @pending_trades.each do |trade|
            %tr
              %td
                %strong
                  #{trade.from_user_name} 
                proposed trading #{trade.from_chore_name} for #{trade.to_chore_name} (#{trade.to_user_name})
              %td{:style => "width:180px"}
                - if trade.from_user_id == @current_user.id
                  = link_to "Retract Trade", retract_group_assigned_chore_trade_path(@group.id,trade.from_chore_id,trade.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-danger ajaxCandidate pull-right'
                - elsif trade.to_user_id == @current_user.id
                  = link_to "Accept Trade", accept_group_assigned_chore_trade_path(@group.id,trade.from_chore_id,trade.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-success ajaxCandidate pull-right', :style => "margin-left:5px"
                  = link_to "Decline Trade", decline_group_assigned_chore_trade_path(@group.id,trade.from_chore_id,trade.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-danger ajaxCandidate pull-right'
      .row
        .span5
          %h3 Upcoming Chores
        .span3{:style => "margin-top:30px;"}
          = link_to "History",chore_history_group_path(@group), :class => "pull-right" 
      %table.table.table-striped.table-bordered.table-condensed
        %tr
          %th Chore
          %th Person
          %th Due Date
          %th Status
        - if @current_chores
          - @current_chores.each do |chore|
            %tr
              %td
                = chore.name
                - if chore.user_id == @current_user.id && chore.status == 'Not Completed' && @group.possible_chore_trades(@current_user).length > 0
                  = link_to "Trade", new_group_assigned_chore_trade_path(@group.id,chore.id), :class => 'pull-right btn btn-mini btn-info modalCandidate'
              %td
                = chore.username
              %td
                = chore.due_date
              %td
                - unless chore.status == "Completed"
                  = link_to chore.status, complete_group_assigned_chore_path(chore.group_id,chore.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-danger ajaxCandidate'
                - else
                  = link_to chore.status, uncomplete_group_assigned_chore_path(chore.group_id,chore.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-success ajaxCandidate'
        - else 
          -@users.each do |user|
            %tr
              %td
              %td
                = user.username
              %td
              %td
                %span.label.label-important
    .row
      .span2.offset2
        = link_to "Invite a Friend", new_group_invitation_path(@group), :class => "btn btn-primary modalCandidate"
      .span2.offset1
        = link_to "Add a Chore", new_group_chore_path(@group), :class => "btn btn-primary modalCandidate"
    .row
      %h3 Chore Chart  
      .div 
        = raw(event_calendar)
  / /container
  /
    Le javascript
    \==================================================
  / Placed at the end of the document so the pages load faster
  :javascript
    lineData = #{@group_chores_completed_by_week.map {|x| x.count.to_i}};
    lineDataMax = Math.max.apply(Math, lineData);
    var lineChartData = {
            labels : #{@group_chores_completed_by_week.map {|x| x.date.to_date.strftime("%B %d").to_s }},
            datasets : [
                    {
                            fillColor : "rgba(96,247,66,0.5)",
                            strokeColor : "rgba(96,247,66,1)",
                            pointColor : "rgba(96,247,66,1)",
                            pointStrokeColor : "#fff",
                            data : lineData
                    }
            ]
            
    }
    var lineChartOptions = {
            scaleOverride : true,
            scaleStepWidth: 1,
            scaleStartValue : 0,
            scaleSteps : lineDataMax,
            displayNoDataMsg : true,
            noDataMsg : "No data yet!",
    }
    new Chart(document.getElementById("lineGraph").getContext("2d")).Line(lineChartData, lineChartOptions);

    var radarChartData = {
            labels : #{@group_percentage_chores_completed_by_user.map(&:username)},
            datasets : [
                    {
                            fillColor : "rgba(248,54,47,0.5)",
                            strokeColor : "rgba(248,54,47,1)",
                            pointColor : "rgba(248,54,47,1)",
                            pointStrokeColor : "#fff",
                            data : #{@group_percentage_chores_completed_by_user.map(&:percent)}
                    }
            ]
    }
    var radarChartOptions = {
            scaleShowLabels : true,
            scaleOverride : true,
            scaleSteps : 5,
            scaleStepWidth : 20,
            scaleStartValue : 0,
            labelTruncate : true,
            displayNoDataMsg : true,
            noDataMsg : "No data yet!",
    }
    new Chart(document.getElementById("radarGraph").getContext("2d")).Radar(radarChartData, radarChartOptions);
    
    var barChartData = {
      labels : #{@group_percentage_completed_by_chore.map { |x| x.name.to_s }},
      datasets : [
        {
          fillColor : "#69D2E7",
          strokeColor : "#5AB5C7",
          data : #{@group_percentage_completed_by_chore.map { |x| x.percent.to_i }}
        }
      ]
    }
    
    var barChartOptions = {
      	    scaleOverride : true,
            scaleSteps : 10,
            scaleStartValue : 0,
            scaleStepWidth : 10,
            displayNoDataMsg : true,
            noDataMsg : "No data yet!",
    }
    new Chart(document.getElementById("barGraph").getContext("2d")).Bar(barChartData, barChartOptions);