config/routes.rb
RevolvingChore::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :groups do
    collection do
      post 'assigned_chores/add_more_assigned_chores'
    end 
    member do
      delete 'remove_user_from_group'
      get 'chore_history'
    end
    resources :assigned_chores do
      resources :ratings do
        collection do
          post 'upsert'
          post 'archive'
        end
      end
      resources :trades do
        member do
          post 'accept'
          post 'decline'
          post 'retract'
        end
      end
      collection do
        post 'create_initial_assigned_chores'
      end
      member do
        post 'complete'
        post 'uncomplete'
      end
    end
    resources :chores
    resources :invitations do
      member do
        get 'accept'
      end
    end
  end

  resources :users do
    member do
      get 'chore_history'
    end
  end

  get "home/index"
  get "home/how_this_works"
  get "home/faq"
  get "home/login"
  
  root :to => "home#index"

  post '/oauth/request_token' => 'sessions#new'

  match '/auth/:provider/callback' => 'sessions#create',:as => 'login'
  match '/auth/failure' => 'sessions#failure'
  match '/auth/logout' => 'sessions#destroy',:as => 'logout'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :group_maps
  has_many :groups, :through => :group_maps
  has_many :assigned_chores
  has_many :from_trades, :class_name => "Trade", :foreign_key => "from_user_id"
  has_many :to_trades, :class_name => "Trade", :foreign_key => "to_user_id"
  extend TwilioHelper
  
  attr_accessible :id, :username, :email, :display_name, :monetary_amount_due, 
    :auth_token, :auth_secret, :auth_expiration_date,
    :email_notification, :sms_notification, :phone_number
  
  def self.create_with_omniauth(auth)
    new_user = User.new()
    new_user.provider = auth["provider"]
    new_user.uid = auth["uid"]
    new_user.auth_token = auth["credentials"]["token"]
    new_user.auth_secret = auth["credentials"]["secret"]
    new_user.auth_expiration_date = Time.at(auth["credentials"]["expires_at"]) if auth["credentials"]["expires_at"]
    new_user.username = auth["info"]["name"]
    new_user.email = auth["info"]["email"].presence || auth["extra"]["raw_info"]["email"].presence
    new_user.save
    return new_user
  end
  
  def self.find_and_update_with_omniauth(auth)
    user = find_by_uid_and_provider(auth["uid"],auth["provider"])
    user.update_attributes(:auth_token => auth["credentials"]["token"], 
      :auth_secret => auth["credentials"]["secret"], 
      :auth_expiration_date => (Time.at(auth["credentials"]["expires_at"]) if auth["credentials"]["expires_at"]), 
      :username => auth["info"]["name"].presence || user.username, 
      :email => auth["info"]["email"].presence || auth["extra"]["raw_info"]["email"].presence || user.email) if user
    user
  end
  
  def post(message)
    if self.provider == "facebook"
      user = Koala::Facebook::API.new(self.auth_token)
      user.put_wall_post(message)
    elsif self.provider == "twitter"
      user = Twitter::Client.new(:oauth_token => self.auth_token, :oauth_token_secret => self.auth_secret)
      user.update(message) # Docs use Thread.new(expression)
    end
  end
  
  def notify(upcoming_assigned_chore)
    if self.email_notification && self.email
      UserMailer.notify(upcoming_assigned_chore).deliver
    end
    if self.sms_notification && self.phone_number
      # Send Text
      User.text(self.phone_number,"#{upcoming_assigned_chore.name} is due tomorrow")
    end
  end
  
  
  def current_chores
    assigned_chores = self.assigned_chores
    unless assigned_chores.empty?
      current_chores = assigned_chores.joins(:group).where("start_date <= ? and due_date >= ?", Date.today, Date.today).order('due_date ASC, name ASC')
    else
      return nil
    end
  end
  
  def pending_trades
    pending_trades = self.from_trades.where(:status => 'Pending') + self.to_trades.where(:status => 'Pending')
    unless pending_trades.empty?
      pending_trades
    else
      nil
    end
  end
  
  def chore_history
    self.assigned_chores.where('due_date < ?', Date.today).where("due_date > ?", Date.today - 3.month).order('due_date ASC, name ASC')
  end
  
  def chores_completed_by_week
    self.assigned_chores.select("date_trunc('week',due_date) as date,COUNT(completion_date) as count").where("due_date < ?", Time.now).where("completion_date is not null").group("date_trunc('week',due_date)").order("date_trunc('week',due_date) ASC")
  end
  
  def percentage_chores_completed_by_group
    self.assigned_chores.select("group_name, ROUND(COUNT(completion_date)/COUNT(id)::decimal * 100,2) as percent").where("due_date < ?", Time.now).group("group_name")    
  end
  
  def set_calendar_colors(event_strips)
    #returns hash of groups assigned to colors. Key => Value. groupname => color

    groups = self.groups
    colors = ["#E23939", "#55C6EB", "#3DB638", "#F09C37", "#E4E43D", "#4E4EF7", "#985AF5", "#74DFB0"]
    counter = 0
    group_colors = Hash.new

    groups.each do |group|
      group_colors.merge!(group.name => colors[counter % colors.length])
      counter += 1
    end

    event_strips.collect! do |event_strip|
      event_strip.collect! do |event|
        if event != nil && group_colors.has_key?(event.group_name)
          event.color = group_colors[event.group_name]
          event
        end
      end
    end
    event_strips
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :validate_and_set_allowable_group
  
  def show
    if @current_user.assigned_chores.empty? != true
      @current_chores = @current_user.current_chores
    end

    @month = (params[:month] || (Time.zone || Time).now.month).to_i
    @year = (params[:year] || (Time.zone || Time).now.year).to_i

    @shown_month = Date.civil(@year, @month)

    @event_strips = @current_user.assigned_chores.event_strips_for_month(@shown_month)

    if @current_user.groups.empty? != true
      @event_strips = @current_user.set_calendar_colors(@event_strips)
    end
    
    @pending_trades = @current_user.pending_trades
    @user_chores_completed_by_week = @current_user.chores_completed_by_week
    @user_percentage_chores_completed_by_group = @current_user.percentage_chores_completed_by_group
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        flash[:notice] = "You have successfully updated your account!"
        format.html { redirect_to @user }
        format.json { head :no_content }
      else
        flash[:error] = "Looks like something went wrong."
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def chore_history
    @chore_history = @current_user.chore_history
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user, :html => { :class => 'form-horizontal span8' } do |f|
  .control-group
    = f.label :username, "Name", :class => 'control-label'
    .controls
      = f.text_field :username, :class => 'text_field'    
  .control-group
    = f.label :notification_method, :class => 'control-label'
    .controls
      %label.checkbox
        = f.check_box :email_notification, {:class => 'check_box parent'}
        Email
      .child{:class => ("hide" unless @current_user.email_notification)}
        .control-group
          = f.label :email, "Email Address", :class => 'control-label'
          .controls
            = f.text_field :email, :class => 'text_field'
      %label.checkbox
        = f.check_box :sms_notification, {:class => 'check_box parent'}
        SMS
      .child{:class => ("hide" unless @current_user.sms_notification)}
        .control-group
          = f.label :phone_number, "Phone Number", :class => 'control-label'
          .controls
            = f.text_field :phone_number, :class => 'text_field' # 'bfh-phone', "data-format" => "+1 (ddd) ddd-dddd"
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to "Cancel", :back, :class => 'btn'

app/views/users/chore_history.html.haml
.page-header
  %h1 Your Chore History
  %table.table.table-striped.table-bordered.table-condensed
    %tr
      %th Due Date
      %th Chore
      %th Group
      %th Status
    - if @chore_history
      - @chore_history.each do |chore|
        %tr
          %td
            = chore.due_date
          %td
            = chore.name
          %td
            = chore.group_name
          %td
            - if chore.status == "Completed"
              %span.label.label-success #{chore.status}
            - else
              %span.label.label-important #{chore.status}

app/views/users/edit.html.haml
.page-header
  %h1
    #{@current_user.username}
    %small
      Settings
= render :partial => 'form'

app/views/users/show.html.haml
- content_for :head do
  %title #{@current_user.username}'s Dashboard - Revolving Chore
  %meta{:name => "description", :content => "RevolvingChore is a fully automated chore chart substitute that comes complete with punishments, trading, and much more!"}
= render :partial => 'layouts/alerts'
.page-header
  %h1
    #{@current_user.username}
    %small
      Dashboard
.row
  .span4
    %ul.thumbnails
      %li
        .thumbnail
          %h5 Chores Completed by Week
          %canvas#lineGraph{:height => "150", :width => "280"}
      %li
        .thumbnail
          %h5 Chores Completed by Group (%)
          %canvas#barGraph{:height => "250", :width => "280"}
  .span8
    .row
      - if @pending_trades
        %h3 Your Pending Trades
        %table.table.table-striped.table-condensed
          - @pending_trades.each do |trade|
            - if trade.from_user_id == @current_user.id
              - trade.from_user_name = 'You'
            - if trade.to_user_id == @current_user.id
              - trade.to_user_name = 'You'
            %tr
              %td
                %strong
                  = trade.from_user_name 
                proposed trading #{trade.from_chore_name} for #{trade.to_chore_name} (#{trade.to_user_name})
              %td{:style => "width:180px"}
                - if trade.from_user_id == @current_user.id
                  = link_to "Retract Trade", retract_group_assigned_chore_trade_path(trade.group_id,trade.from_chore_id,trade.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-danger ajaxCandidate pull-right'
                - elsif trade.to_user_id == @current_user.id
                  = link_to "Accept Trade", accept_group_assigned_chore_trade_path(trade.group_id,trade.from_chore_id,trade.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-success ajaxCandidate pull-right', :style => "margin-left:5px"
                  = link_to "Decline Trade", decline_group_assigned_chore_trade_path(trade.group_id,trade.from_chore_id,trade.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-danger ajaxCandidate pull-right'
      .row
        .span5
          %h3 My To Do List
        .span3{:style => "margin-top:30px;"}
          = link_to "History",chore_history_user_path(@current_user), :class => "pull-right"   
      %table.table.table-striped.table-bordered.table-condensed
        %tr
          %th Chore
          %th Group
          %th Due Date
          %th Status
        - if @current_chores
          - @current_chores.each do |chore|
            %tr
              %td
                = chore.name
                - if chore.status == 'Not Completed' && chore.group.possible_chore_trades(@current_user).length > 0
                  = link_to "Trade", new_group_assigned_chore_trade_path(chore.group_id,chore.id), :class => 'pull-right btn btn-mini btn-info modalCandidate'
              %td
                = chore.group_name
              %td
                = chore.due_date
              %td
                - unless chore.status == "Completed"
                  = link_to chore.status, complete_group_assigned_chore_path(chore.group_id,chore.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-danger ajaxCandidate'
                - else
                  = link_to chore.status, uncomplete_group_assigned_chore_path(chore.group_id,chore.id), "data-method" => "post", "data-confirm" => 'Are you sure?', :class => 'btn btn-mini btn-success ajaxCandidate'
    .row
      %h3 This Month's Chores       
      .div 
        = raw(user_event_calendar)
  /
    Le javascript
    \==================================================
  / Placed at the end of the document so the pages load faster
  :javascript
    lineData = #{@user_chores_completed_by_week.map {|x| x.count.to_i}};
    lineDataMax = Math.max.apply(Math, lineData);
    var lineChartData = {
            labels : #{@user_chores_completed_by_week.map {|x| x.date.to_date.strftime("%B %d").to_s }},
            datasets : [
                    {
                            fillColor : "rgba(248,54,47,0.5)",
                            strokeColor : "rgba(248,54,47,1)",
                            pointColor : "rgba(248,54,47,1)",
                            pointStrokeColor : "#fff",
                            data : lineData
                    }
            ]
            
    }
    var lineChartOptions = {
            scaleOverride : true,
            scaleStepWidth: 1,
            scaleStartValue : 0,
            scaleSteps : lineDataMax,
            displayNoDataMsg : true,
            noDataMsg : "No data yet!",
    }
    new Chart(document.getElementById("lineGraph").getContext("2d")).Line(lineChartData, lineChartOptions);

    var barChartData = {
      labels : #{@user_percentage_chores_completed_by_group.map {|x| x.group_name}},
      datasets : [
        {
          fillColor : "#69D2E7",
          strokeColor : "#5AB5C7",
          data : #{@user_percentage_chores_completed_by_group.map { |x| x.percent.to_i }}
        }
      ]
    }
    var barChartOptions = {
            scaleOverride : true,
            scaleSteps : 10,
            scaleStartValue : 0,
            scaleStepWidth : 10,
            displayNoDataMsg : true,
            noDataMsg : "No data yet!",
    }
    new Chart(document.getElementById("barGraph").getContext("2d")).Bar(barChartData, barChartOptions);
    