config/routes.rb
RevolvingChore::Application.routes.draw do
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :groups do
    collection do
      post 'assigned_chores/add_more_assigned_chores'
    end 
    member do
      delete 'remove_user_from_group'
      get 'chore_history'
    end
    resources :assigned_chores do
      resources :ratings do
        collection do
          post 'upsert'
          post 'archive'
        end
      end
      resources :trades do
        member do
          post 'accept'
          post 'decline'
          post 'retract'
        end
      end
      collection do
        post 'create_initial_assigned_chores'
      end
      member do
        post 'complete'
        post 'uncomplete'
      end
    end
    resources :chores
    resources :invitations do
      member do
        get 'accept'
      end
    end
  end

  resources :users do
    member do
      get 'chore_history'
    end
  end

  get "home/index"
  get "home/how_this_works"
  get "home/faq"
  get "home/login"
  
  root :to => "home#index"

  post '/oauth/request_token' => 'sessions#new'

  match '/auth/:provider/callback' => 'sessions#create',:as => 'login'
  match '/auth/failure' => 'sessions#failure'
  match '/auth/logout' => 'sessions#destroy',:as => 'logout'

  

end

app/views/layouts/_alerts.html.haml
- if(flash[:notice])
  .alert.alert-success
    %button.close{"type" => "button", "data-dismiss" => "alert"} &times;
    = flash[:notice]
- elsif(flash[:error])
  .alert.alert-error
    %button.close{"type" => "button", "data-dismiss" => "alert"} &times;
    = flash[:error]

app/views/layouts/_login_nav.html.haml
= link_to 'Revolving Chore', user_path(@current_user.id), :class => "brand"
.nav-collapse.collapse
  %ul.nav
    %li{:class => (params[:controller] == "users" && params[:action] == "show" ? "active" : "")}
      = link_to user_path(@current_user.id) do
        %i.icon-home.icon-white
        Home
    - unless @current_user.groups.count == 0
      %li{:class => "dropdown #{params[:controller] == 'groups' ? 'active' : ''}"}
        %a{:class => "dropdown-toggle", :href => "#", "data-toggle" => "dropdown"}
          %i.icon-briefcase.icon-white 
          My Groups
          %b.caret
        %ul.dropdown-menu
          - @current_user.groups.each do |group|
            %li 
              = link_to group.name, group_path(group.id)
          %li.divider
          %li 
            = link_to new_group_path do
              %i.icon-plus-sign
              Create a Group
    - else
      %li{:class => "dropdown #{params[:controller] == "groups" ? "active" : ""}"}
        = link_to 'Create a Group', new_group_path    
  %ul.nav.pull-right 
    %li{:class => "dropdown #{params[:controller] == 'users' && params[:action] == 'edit' ? 'active' : ''}"}
      %a{:class => "dropdown-toggle", :href => "#", "data-toggle" => "dropdown"} 
        %i.icon-user.icon-white
        Account
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to edit_user_path(@current_user.id) do
            %i.icon-cog
            Settings
        %li
          = link_to logout_path do
            %i.icon-share-alt
            Log Out

app/views/layouts/_logout_nav.html.haml
= link_to 'Revolving Chore', home_index_path, :class => "brand"
.nav-collapse.collapse
  %ul.nav
    %li{:class => (params[:action] == "index" ? "active" : "")}
      = link_to 'Home', home_index_path
    %li{:class => (params[:action] == "about" ? "active" : "")}
      = link_to 'How this works', home_how_this_works_path
    -# %li{:class => (params[:action] == "faq" ? "active" : "")}
      -# = link_to 'FAQ', home_faq_path
  %ul.nav.pull-right 
    %li.dropdown
      %a{:class => "dropdown-toggle", :href => "#", "data-toggle" => "dropdown"} 
        Sign In
        %b.caret
      %ul.dropdown-menu
        - if @current_env == "development"
          %li
            = link_to "Sign in as developer","/auth/developer"
        %li
          = link_to "/auth/facebook" do
            = image_tag "facebook_logo.png"
            Sign in with Facebook
            
        %li
          = link_to "/auth/twitter" do
            = image_tag "twitter_logo.png"
            Sign in with Twitter
            

app/views/layouts/application.html.haml
!!!
%html
  %head
    - if content_for? :head
      = yield :head
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application" 
    = csrf_meta_tags
    = favicon_link_tag "favicon.ico"
  %body.lightblue
    #background-gradient
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
            %a.brand
          - if @current_user
            = render :partial => "/layouts/login_nav"
          - else
            = render :partial => "/layouts/logout_nav"
          / /.nav-collapse
    .container#main
      = yield
    %hr
      .container
        .footer
          =image_tag "LH_Logo3.png"
          %span © Lloyd House Studios 2013  

-if ENV["RACK_ENV"] == "production"
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41458106-1', 'revolvingchore.com');
    ga('send', 'pageview');

app/views/layouts/email.html.haml
!!!
%html
  %head
    %title RevolvingChore
    = stylesheet_link_tag "application", :media => "all"
  %body
    = yield